// Generated by Cadence Encounter(R) RTL Compiler RC12.22 - v12.20-s014_1
// Verification Directory fv/shift_adder 
module shift_adder (
	clock, 
	reset, 
	lefthand, 
	righthand, 
	result);
   input clock;
   input reset;
   input [7:0] lefthand;
   input [7:0] righthand;
   output [8:0] result;

   // Internal wires
   wire clock__L2_N0;
   wire clock__L1_N0;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;

   assign result[8] = 1'b0 ;

   INVCKX16 clock__L2_I0 (.O(clock__L2_N0), 
	.I(clock__L1_N0));
   INVCKX20 clock__L1_I0 (.O(clock__L1_N0), 
	.I(clock));
   QDFFX1 \result_reg[7]  (.Q(result[7]), 
	.D(n_41), 
	.CK(clock__L2_N0));
   MUXB2X1 g434 (.S(n_39), 
	.O(n_41), 
	.EB(reset), 
	.B(n_3), 
	.A(n_2));
   QDFFX1 \result_reg[6]  (.Q(result[6]), 
	.D(n_40), 
	.CK(clock__L2_N0));
   MUXB2X1 g436 (.S(n_38), 
	.O(n_40), 
	.EB(reset), 
	.B(n_21), 
	.A(n_22));
   AO12X1 g438 (.O(n_39), 
	.B2(n_8), 
	.B1(n_38), 
	.A1(n_9));
   QDFFX1 \result_reg[5]  (.Q(result[5]), 
	.D(n_37), 
	.CK(clock__L2_N0));
   MUXB2X1 g439 (.S(n_36), 
	.O(n_37), 
	.EB(reset), 
	.B(n_27), 
	.A(n_28));
   AO12X1 g441 (.O(n_38), 
	.B2(n_15), 
	.B1(n_36), 
	.A1(n_16));
   QDFFX1 \result_reg[4]  (.Q(result[4]), 
	.D(n_35), 
	.CK(clock__L2_N0));
   MUXB2X1 g442 (.S(n_34), 
	.O(n_35), 
	.EB(reset), 
	.B(n_17), 
	.A(n_18));
   AO12X1 g444 (.O(n_36), 
	.B2(n_4), 
	.B1(n_34), 
	.A1(n_5));
   QDFFX1 \result_reg[3]  (.Q(result[3]), 
	.D(n_33), 
	.CK(clock__L2_N0));
   MUXB2X1 g445 (.S(n_32), 
	.O(n_33), 
	.EB(reset), 
	.B(n_19), 
	.A(n_20));
   QDFFX1 \result_reg[2]  (.Q(result[2]), 
	.D(n_31), 
	.CK(clock__L2_N0));
   AO12X1 g447 (.O(n_34), 
	.B2(n_6), 
	.B1(n_32), 
	.A1(n_7));
   QDFFX1 \result_reg[1]  (.Q(result[1]), 
	.D(n_29), 
	.CK(clock__L2_N0));
   MUXB2X1 g448 (.S(n_30), 
	.O(n_31), 
	.EB(reset), 
	.B(n_23), 
	.A(n_24));
   AO12X1 g450 (.O(n_32), 
	.B2(n_10), 
	.B1(n_30), 
	.A1(n_11));
   MUXB2X1 g451 (.S(n_14), 
	.O(n_29), 
	.EB(reset), 
	.B(n_1), 
	.A(n_26));
   QDFFX1 \result_reg[0]  (.Q(result[0]), 
	.D(n_25), 
	.CK(clock__L2_N0));
   INVX1 g456 (.O(n_28), 
	.I(n_27));
   OAI12X1 g453 (.O(n_30), 
	.B2(n_26), 
	.B1(n_13), 
	.A1(n_12));
   MUXB2X1 g454 (.S(lefthand[0]), 
	.O(n_25), 
	.EB(reset), 
	.B(n_0), 
	.A(righthand[0]));
   INVX1 g459 (.O(n_24), 
	.I(n_23));
   INVX1 g461 (.O(n_22), 
	.I(n_21));
   INVX1 g463 (.O(n_20), 
	.I(n_19));
   INVX1 g465 (.O(n_18), 
	.I(n_17));
   OR2B1XLP g457 (.O(n_27), 
	.I1(n_16), 
	.B1(n_15));
   OR2B1XLP g458 (.O(n_14), 
	.I1(n_13), 
	.B1(n_12));
   OR2B1XLP g460 (.O(n_23), 
	.I1(n_11), 
	.B1(n_10));
   OR2B1XLP g462 (.O(n_21), 
	.I1(n_9), 
	.B1(n_8));
   OR2B1XLP g464 (.O(n_19), 
	.I1(n_7), 
	.B1(n_6));
   OR2B1XLP g466 (.O(n_17), 
	.I1(n_5), 
	.B1(n_4));
   INVX1 g467 (.O(n_3), 
	.I(n_2));
   MAOI1X1 g468 (.O(n_2), 
	.B2(lefthand[7]), 
	.B1(righthand[7]), 
	.A2(righthand[7]), 
	.A1(lefthand[7]));
   INVXLP g455 (.O(n_1), 
	.I(n_26));
   AN2X1 g469 (.O(n_11), 
	.I2(righthand[2]), 
	.I1(lefthand[2]));
   ND2X1 g479 (.O(n_12), 
	.I2(righthand[1]), 
	.I1(lefthand[1]));
   AN2X1 g470 (.O(n_5), 
	.I2(righthand[4]), 
	.I1(lefthand[4]));
   ND2X1 g471 (.O(n_26), 
	.I2(righthand[0]), 
	.I1(lefthand[0]));
   NR2X1 g472 (.O(n_13), 
	.I2(righthand[1]), 
	.I1(lefthand[1]));
   AN2X1 g473 (.O(n_9), 
	.I2(righthand[6]), 
	.I1(lefthand[6]));
   OR2X1 g474 (.O(n_8), 
	.I2(righthand[6]), 
	.I1(lefthand[6]));
   OR2X1 g476 (.O(n_4), 
	.I2(righthand[4]), 
	.I1(lefthand[4]));
   OR2X1 g481 (.O(n_15), 
	.I2(righthand[5]), 
	.I1(lefthand[5]));
   AN2X1 g478 (.O(n_16), 
	.I2(righthand[5]), 
	.I1(lefthand[5]));
   OR2X1 g475 (.O(n_10), 
	.I2(righthand[2]), 
	.I1(lefthand[2]));
   AN2X1 g480 (.O(n_7), 
	.I2(righthand[3]), 
	.I1(lefthand[3]));
   OR2X1 g477 (.O(n_6), 
	.I2(righthand[3]), 
	.I1(lefthand[3]));
   INVX1 g482 (.O(n_0), 
	.I(righthand[0]));
endmodule

