// Generated by Cadence Encounter(R) RTL Compiler RC9.1.203 - v09.10-s242_1
module multiplier (
	x, 
	y, 
	clock, 
	reset, 
	enable, 
	z);
   input [3:0] x;
   input [3:0] y;
   input clock;
   input reset;
   input enable;
   output [7:0] z;

   // Internal wires
   wire clock__L2_N0;
   wire clock__L1_N0;
   wire [7:0] pp1;
   wire [7:0] pp0;
   wire [7:0] pp3;
   wire [7:0] pp2;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;

   INVCKX20 clock__L2_I0 (.O(clock__L2_N0), 
	.I(clock__L1_N0));
   INVCKX20 clock__L1_I0 (.O(clock__L1_N0), 
	.I(clock));
   QDFCRBX1 \z_reg[7]  (.RB(enable), 
	.Q(z[7]), 
	.D(n_40), 
	.CK(clock__L2_N0));
   QDFCRBX1 \z_reg[6]  (.RB(enable), 
	.Q(z[6]), 
	.D(n_39), 
	.CK(clock__L2_N0));
   OAI112X1 g1151 (.O(n_40), 
	.C2(n_18), 
	.C1(n_38), 
	.B1(n_2), 
	.A1(n_19));
   MOAI1X1 g1153 (.O(n_39), 
	.B2(n_37), 
	.B1(n_38), 
	.A2(n_37), 
	.A1(n_38));
   QDFCRBX1 \z_reg[5]  (.RB(enable), 
	.Q(z[5]), 
	.D(n_36), 
	.CK(clock__L2_N0));
   AOI12X1 g1155 (.O(n_38), 
	.B2(n_29), 
	.B1(n_35), 
	.A1(n_30));
   QDFCRBX1 \z_reg[4]  (.RB(enable), 
	.Q(z[4]), 
	.D(n_33), 
	.CK(clock__L2_N0));
   MOAI1X1 g1156 (.O(n_36), 
	.B2(n_34), 
	.B1(n_35), 
	.A2(n_34), 
	.A1(n_35));
   FA1X1 g1157 (.S(n_33), 
	.CO(n_35), 
	.CI(n_31), 
	.B(n_25), 
	.A(n_24));
   QDFCRBX1 \z_reg[3]  (.RB(enable), 
	.Q(z[3]), 
	.D(n_32), 
	.CK(clock__L2_N0));
   FA1X1 g1159 (.S(n_32), 
	.CO(n_31), 
	.CI(n_26), 
	.B(n_4), 
	.A(n_27));
   QDFFX1 \z_reg[2]  (.Q(z[2]), 
	.D(n_28), 
	.CK(clock__L2_N0));
   OR2B1XLP g1160 (.O(n_34), 
	.I1(n_30), 
	.B1(n_29));
   AOI112X1 g1164 (.O(n_28), 
	.C2(n_17), 
	.C1(n_16), 
	.B1(n_5), 
	.A1(n_27));
   FA1X1 g1166 (.S(n_26), 
	.CO(n_25), 
	.CI(n_11), 
	.B(pp1[3]), 
	.A(n_1));
   ND2X1 g1163 (.O(n_29), 
	.I2(n_21), 
	.I1(n_20));
   MOAI1X1 g1165 (.O(n_24), 
	.B2(n_22), 
	.B1(n_23), 
	.A2(n_22), 
	.A1(n_23));
   NR2X1 g1162 (.O(n_30), 
	.I2(n_20), 
	.I1(n_21));
   AN2B1XLP g1167 (.O(n_37), 
	.I1(n_19), 
	.B1(n_18));
   NR2X1 g1170 (.O(n_27), 
	.I2(n_16), 
	.I1(n_17));
   MAOI222X1 g1172 (.O(n_20), 
	.C1(n_22), 
	.B1(pp1[4]), 
	.A1(n_6));
   QDFFX1 \z_reg[1]  (.Q(z[1]), 
	.D(n_3), 
	.CK(clock__L2_N0));
   NR2X1 g1168 (.O(n_18), 
	.I2(n_15), 
	.I1(n_14));
   ND2X1 g1169 (.O(n_19), 
	.I2(n_14), 
	.I1(n_15));
   MAOI1X1 g1171 (.O(n_23), 
	.B2(n_13), 
	.B1(pp1[4]), 
	.A2(pp1[4]), 
	.A1(n_13));
   MAOI1X1 g1176 (.O(n_16), 
	.B2(n_12), 
	.B1(pp1[2]), 
	.A2(pp1[2]), 
	.A1(n_12));
   MOAI1X1 g1198 (.O(n_11), 
	.B2(pp0[3]), 
	.B1(n_10), 
	.A2(pp0[3]), 
	.A1(n_10));
   MAOI1X1 g1174 (.O(n_21), 
	.B2(n_8), 
	.B1(n_9), 
	.A2(n_9), 
	.A1(n_8));
   MOAI1X1 g1175 (.O(n_14), 
	.B2(pp3[6]), 
	.B1(n_7), 
	.A2(pp3[6]), 
	.A1(n_7));
   INVXLP g1177 (.O(n_6), 
	.I(n_13));
   QDFZCRBX1 \pp0_reg[3]  (.TD(pp0[3]), 
	.SEL(n_5), 
	.RB(y[0]), 
	.Q(pp0[3]), 
	.D(x[3]), 
	.CK(clock__L2_N0));
   QDFZCRBX1 \pp0_reg[2]  (.TD(pp0[2]), 
	.SEL(n_5), 
	.RB(y[0]), 
	.Q(pp0[2]), 
	.D(x[2]), 
	.CK(clock__L2_N0));
   QDFZCRBX1 \pp2_reg[2]  (.TD(pp2[2]), 
	.SEL(n_5), 
	.RB(y[2]), 
	.Q(pp2[2]), 
	.D(x[0]), 
	.CK(clock__L2_N0));
   QDFZCRBX1 \pp2_reg[5]  (.TD(pp2[5]), 
	.SEL(n_5), 
	.RB(y[2]), 
	.Q(pp2[5]), 
	.D(x[3]), 
	.CK(clock__L2_N0));
   QDFZCRBX1 \pp3_reg[3]  (.TD(pp3[3]), 
	.SEL(n_5), 
	.RB(y[3]), 
	.Q(pp3[3]), 
	.D(x[0]), 
	.CK(clock__L2_N0));
   QDFZCRBX1 \pp3_reg[4]  (.TD(pp3[4]), 
	.SEL(n_5), 
	.RB(y[3]), 
	.Q(pp3[4]), 
	.D(x[1]), 
	.CK(clock__L2_N0));
   QDFZCRBX1 \pp1_reg[2]  (.TD(pp1[2]), 
	.SEL(n_5), 
	.RB(y[1]), 
	.Q(pp1[2]), 
	.D(x[1]), 
	.CK(clock__L2_N0));
   QDFZCRBX1 \pp3_reg[5]  (.TD(pp3[5]), 
	.SEL(n_5), 
	.RB(y[3]), 
	.Q(pp3[5]), 
	.D(x[2]), 
	.CK(clock__L2_N0));
   QDFZCRBX1 \pp0_reg[1]  (.TD(pp0[1]), 
	.SEL(n_5), 
	.RB(y[0]), 
	.Q(pp0[1]), 
	.D(x[1]), 
	.CK(clock__L2_N0));
   QDFZCRBX1 \pp1_reg[4]  (.TD(pp1[4]), 
	.SEL(n_5), 
	.RB(y[1]), 
	.Q(pp1[4]), 
	.D(x[3]), 
	.CK(clock__L2_N0));
   QDFZCRBX1 \pp2_reg[3]  (.TD(pp2[3]), 
	.SEL(n_5), 
	.RB(y[2]), 
	.Q(pp2[3]), 
	.D(x[1]), 
	.CK(clock__L2_N0));
   QDFZCRBX1 \pp3_reg[6]  (.TD(pp3[6]), 
	.SEL(n_5), 
	.RB(y[3]), 
	.Q(pp3[6]), 
	.D(x[3]), 
	.CK(clock__L2_N0));
   QDFZCRBX1 \pp1_reg[3]  (.TD(pp1[3]), 
	.SEL(n_5), 
	.RB(y[1]), 
	.Q(pp1[3]), 
	.D(x[2]), 
	.CK(clock__L2_N0));
   QDFZCRBX1 \pp2_reg[4]  (.TD(pp2[4]), 
	.SEL(n_5), 
	.RB(y[2]), 
	.Q(pp2[4]), 
	.D(x[2]), 
	.CK(clock__L2_N0));
   AN2B1XLP g1194 (.O(n_4), 
	.I1(pp1[2]), 
	.B1(n_12));
   QDFZCRBX1 \pp0_reg[0]  (.TD(pp0[0]), 
	.SEL(n_5), 
	.RB(y[0]), 
	.Q(pp0[0]), 
	.D(x[0]), 
	.CK(clock__L2_N0));
   AN2B1XLP g1195 (.O(n_15), 
	.I1(n_8), 
	.B1(n_9));
   MUXB2X1 g1197 (.S(pp0[1]), 
	.O(n_3), 
	.EB(n_5), 
	.B(n_0), 
	.A(pp1[1]));
   QDFZCRBX1 \pp1_reg[1]  (.TD(pp1[1]), 
	.SEL(n_5), 
	.RB(y[1]), 
	.Q(pp1[1]), 
	.D(x[0]), 
	.CK(clock__L2_N0));
   OR2B1XLP g1196 (.O(n_2), 
	.I1(n_7), 
	.B1(pp3[6]));
   MAOI222X1 g1199 (.O(n_13), 
	.C1(pp0[3]), 
	.B1(pp3[3]), 
	.A1(pp2[3]));
   QDFCRBX1 \z_reg[0]  (.RB(enable), 
	.Q(z[0]), 
	.D(pp0[0]), 
	.CK(clock__L2_N0));
   XNR2X1 g1201 (.O(n_10), 
	.I2(pp2[3]), 
	.I1(pp3[3]));
   XOR2X1 g1202 (.O(n_22), 
	.I2(pp2[4]), 
	.I1(pp3[4]));
   XOR2X1 g1203 (.O(n_8), 
	.I2(pp2[5]), 
	.I1(pp3[5]));
   XNR2X1 g1204 (.O(n_12), 
	.I2(pp2[2]), 
	.I1(pp0[2]));
   ND2X1 g1207 (.O(n_9), 
	.I2(pp2[4]), 
	.I1(pp3[4]));
   ND2X1 g1205 (.O(n_17), 
	.I2(pp1[1]), 
	.I1(pp0[1]));
   ND2X1 g1206 (.O(n_7), 
	.I2(pp2[5]), 
	.I1(pp3[5]));
   AN2X1 g1208 (.O(n_1), 
	.I2(pp2[2]), 
	.I1(pp0[2]));
   INVXLP g1210 (.O(n_0), 
	.I(pp1[1]));
   INVCKX1 g1209 (.O(n_5), 
	.I(enable));
endmodule

