
// Generated by Cadence Encounter(R) RTL Compiler RC9.1.203 - v09.10-s242_1

module multiplier(x, y, clock, reset, enable, z);
  input [3:0] x, y;
  input clock, reset, enable;
  output [7:0] z;
  wire [3:0] x, y;
  wire clock, reset, enable;
  wire [7:0] z;
  wire [7:0] pp1;
  wire [7:0] pp0;
  wire [7:0] pp3;
  wire [7:0] pp2;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40;
  QDFCRBX1 \z_reg[7] (.CK (clock), .D (n_40), .RB (enable), .Q (z[7]));
  QDFCRBX1 \z_reg[6] (.CK (clock), .D (n_39), .RB (enable), .Q (z[6]));
  OAI112X1 g1151(.A1 (n_19), .B1 (n_2), .C1 (n_38), .C2 (n_18), .O
       (n_40));
  MOAI1X1 g1153(.A1 (n_38), .A2 (n_37), .B1 (n_38), .B2 (n_37), .O
       (n_39));
  QDFCRBX1 \z_reg[5] (.CK (clock), .D (n_36), .RB (enable), .Q (z[5]));
  AOI12X1 g1155(.A1 (n_30), .B1 (n_35), .B2 (n_29), .O (n_38));
  QDFCRBX1 \z_reg[4] (.CK (clock), .D (n_33), .RB (enable), .Q (z[4]));
  MOAI1X1 g1156(.A1 (n_35), .A2 (n_34), .B1 (n_35), .B2 (n_34), .O
       (n_36));
  FA1X1 g1157(.A (n_24), .B (n_25), .CI (n_31), .S (n_33), .CO (n_35));
  QDFCRBX1 \z_reg[3] (.CK (clock), .D (n_32), .RB (enable), .Q (z[3]));
  FA1X1 g1159(.A (n_27), .B (n_4), .CI (n_26), .S (n_32), .CO (n_31));
  QDFFX1 \z_reg[2] (.CK (clock), .D (n_28), .Q (z[2]));
  OR2B1XLP g1160(.I1 (n_30), .B1 (n_29), .O (n_34));
  AOI112X1 g1164(.A1 (n_27), .B1 (n_5), .C1 (n_16), .C2 (n_17), .O
       (n_28));
  FA1X1 g1166(.A (n_1), .B (pp1[3]), .CI (n_11), .S (n_26), .CO (n_25));
  ND2X1 g1163(.I1 (n_20), .I2 (n_21), .O (n_29));
  MOAI1X1 g1165(.A1 (n_23), .A2 (n_22), .B1 (n_23), .B2 (n_22), .O
       (n_24));
  NR2X1 g1162(.I1 (n_21), .I2 (n_20), .O (n_30));
  AN2B1XLP g1167(.I1 (n_19), .B1 (n_18), .O (n_37));
  NR2X1 g1170(.I1 (n_17), .I2 (n_16), .O (n_27));
  MAOI222X1 g1172(.A1 (n_6), .B1 (pp1[4]), .C1 (n_22), .O (n_20));
  QDFFX1 \z_reg[1] (.CK (clock), .D (n_3), .Q (z[1]));
  NR2X1 g1168(.I1 (n_14), .I2 (n_15), .O (n_18));
  ND2X1 g1169(.I1 (n_15), .I2 (n_14), .O (n_19));
  MAOI1X1 g1171(.A1 (n_13), .A2 (pp1[4]), .B1 (pp1[4]), .B2 (n_13), .O
       (n_23));
  MAOI1X1 g1176(.A1 (n_12), .A2 (pp1[2]), .B1 (pp1[2]), .B2 (n_12), .O
       (n_16));
  MOAI1X1 g1198(.A1 (n_10), .A2 (pp0[3]), .B1 (n_10), .B2 (pp0[3]), .O
       (n_11));
  MAOI1X1 g1174(.A1 (n_8), .A2 (n_9), .B1 (n_9), .B2 (n_8), .O (n_21));
  MOAI1X1 g1175(.A1 (n_7), .A2 (pp3[6]), .B1 (n_7), .B2 (pp3[6]), .O
       (n_14));
  INVXLP g1177(.I (n_13), .O (n_6));
  QDFZCRBX1 \pp0_reg[3] (.CK (clock), .D (x[3]), .RB (y[0]), .TD
       (pp0[3]), .SEL (n_5), .Q (pp0[3]));
  QDFZCRBX1 \pp0_reg[2] (.CK (clock), .D (x[2]), .RB (y[0]), .TD
       (pp0[2]), .SEL (n_5), .Q (pp0[2]));
  QDFZCRBX1 \pp2_reg[2] (.CK (clock), .D (x[0]), .RB (y[2]), .TD
       (pp2[2]), .SEL (n_5), .Q (pp2[2]));
  QDFZCRBX1 \pp2_reg[5] (.CK (clock), .D (x[3]), .RB (y[2]), .TD
       (pp2[5]), .SEL (n_5), .Q (pp2[5]));
  QDFZCRBX1 \pp3_reg[3] (.CK (clock), .D (x[0]), .RB (y[3]), .TD
       (pp3[3]), .SEL (n_5), .Q (pp3[3]));
  QDFZCRBX1 \pp3_reg[4] (.CK (clock), .D (x[1]), .RB (y[3]), .TD
       (pp3[4]), .SEL (n_5), .Q (pp3[4]));
  QDFZCRBX1 \pp1_reg[2] (.CK (clock), .D (x[1]), .RB (y[1]), .TD
       (pp1[2]), .SEL (n_5), .Q (pp1[2]));
  QDFZCRBX1 \pp3_reg[5] (.CK (clock), .D (x[2]), .RB (y[3]), .TD
       (pp3[5]), .SEL (n_5), .Q (pp3[5]));
  QDFZCRBX1 \pp0_reg[1] (.CK (clock), .D (x[1]), .RB (y[0]), .TD
       (pp0[1]), .SEL (n_5), .Q (pp0[1]));
  QDFZCRBX1 \pp1_reg[4] (.CK (clock), .D (x[3]), .RB (y[1]), .TD
       (pp1[4]), .SEL (n_5), .Q (pp1[4]));
  QDFZCRBX1 \pp2_reg[3] (.CK (clock), .D (x[1]), .RB (y[2]), .TD
       (pp2[3]), .SEL (n_5), .Q (pp2[3]));
  QDFZCRBX1 \pp3_reg[6] (.CK (clock), .D (x[3]), .RB (y[3]), .TD
       (pp3[6]), .SEL (n_5), .Q (pp3[6]));
  QDFZCRBX1 \pp1_reg[3] (.CK (clock), .D (x[2]), .RB (y[1]), .TD
       (pp1[3]), .SEL (n_5), .Q (pp1[3]));
  QDFZCRBX1 \pp2_reg[4] (.CK (clock), .D (x[2]), .RB (y[2]), .TD
       (pp2[4]), .SEL (n_5), .Q (pp2[4]));
  AN2B1XLP g1194(.I1 (pp1[2]), .B1 (n_12), .O (n_4));
  QDFZCRBX1 \pp0_reg[0] (.CK (clock), .D (x[0]), .RB (y[0]), .TD
       (pp0[0]), .SEL (n_5), .Q (pp0[0]));
  AN2B1XLP g1195(.I1 (n_8), .B1 (n_9), .O (n_15));
  MUXB2X1 g1197(.S (pp0[1]), .A (pp1[1]), .B (n_0), .EB (n_5), .O
       (n_3));
  QDFZCRBX1 \pp1_reg[1] (.CK (clock), .D (x[0]), .RB (y[1]), .TD
       (pp1[1]), .SEL (n_5), .Q (pp1[1]));
  OR2B1XLP g1196(.I1 (n_7), .B1 (pp3[6]), .O (n_2));
  MAOI222X1 g1199(.A1 (pp2[3]), .B1 (pp3[3]), .C1 (pp0[3]), .O (n_13));
  QDFCRBX1 \z_reg[0] (.CK (clock), .D (pp0[0]), .RB (enable), .Q
       (z[0]));
  XNR2X1 g1201(.I1 (pp3[3]), .I2 (pp2[3]), .O (n_10));
  XOR2X1 g1202(.I1 (pp3[4]), .I2 (pp2[4]), .O (n_22));
  XOR2X1 g1203(.I1 (pp3[5]), .I2 (pp2[5]), .O (n_8));
  XNR2X1 g1204(.I1 (pp0[2]), .I2 (pp2[2]), .O (n_12));
  ND2X1 g1207(.I1 (pp3[4]), .I2 (pp2[4]), .O (n_9));
  ND2X1 g1205(.I1 (pp0[1]), .I2 (pp1[1]), .O (n_17));
  ND2X1 g1206(.I1 (pp3[5]), .I2 (pp2[5]), .O (n_7));
  AN2X1 g1208(.I1 (pp0[2]), .I2 (pp2[2]), .O (n_1));
  INVXLP g1210(.I (pp1[1]), .O (n_0));
  INVCKX1 g1209(.I (enable), .O (n_5));
endmodule

