
// Generated by Cadence Encounter(R) RTL Compiler RC9.1.203 - v09.10-s242_1

module clock_divider(clock, reset, enable_all, enable_clk1,
     enable_clk2, enable_clk3, clk1, clk2, clk3);
  input clock, reset, enable_all, enable_clk1, enable_clk2, enable_clk3;
  output clk1, clk2, clk3;
  wire clock, reset, enable_all, enable_clk1, enable_clk2, enable_clk3;
  wire clk1, clk2, clk3;
  wire [3:0] clk1_counter;
  wire [2:0] clk2_counter;
  wire [1:0] clk3_counter;
  wire clk1_internal, clk2_internal, clk3_internal, n_0, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_20, n_21, n_22, n_27;
  wire n_29, n_30, n_31, n_32, n_33;
  DFCLRBX1 \clk1_counter_reg[3] (.CK (clock), .D (clk1_counter[3]), .LD
       (n_11), .RB (n_21), .Q (), .QB (clk1_counter[3]));
  QDFFX1 clk1_internal_reg(.CK (clock), .D (n_22), .Q (clk1_internal));
  QDFFX1 clk2_internal_reg(.CK (clock), .D (n_20), .Q (clk2_internal));
  OAI112X1 g546(.A1 (n_16), .B1 (n_21), .C1 (n_15), .C2
       (clk1_internal), .O (n_22));
  DFCLRBX1 \clk1_counter_reg[2] (.CK (clock), .D (clk1_counter[2]), .LD
       (n_10), .RB (n_21), .Q (), .QB (clk1_counter[2]));
  QDFFX1 clk3_internal_reg(.CK (clock), .D (n_14), .Q (clk3_internal));
  OAI112X1 g550(.A1 (n_13), .B1 (n_21), .C1 (n_12), .C2
       (clk2_internal), .O (n_20));
  DFCLRBX1 \clk2_counter_reg[2] (.CK (clock), .D (clk2_counter[2]), .LD
       (n_0), .RB (n_21), .Q (), .QB (clk2_counter[2]));
  INVTX1 clk1_tri(.I (n_33), .E (n_30), .O (clk1));
  INVTX1 clk2_tri(.I (n_32), .E (n_29), .O (clk2));
  INVTX1 clk3_tri(.I (n_31), .E (n_27), .O (clk3));
  ND2X1 g552(.I1 (n_15), .I2 (clk1_internal), .O (n_16));
  OAI112X1 g545(.A1 (n_9), .B1 (n_21), .C1 (n_8), .C2 (clk3_internal),
       .O (n_14));
  DFFX1 clk2_reg57(.CK (clock), .D (n_6), .Q (), .QB (n_29));
  ND2X1 g557(.I1 (n_12), .I2 (clk2_internal), .O (n_13));
  QDFFX1 \clk2_counter_reg[0] (.CK (clock), .D (n_3), .Q
       (clk2_counter[0]));
  DFCLRBX1 \clk3_counter_reg[1] (.CK (clock), .D (clk3_counter[1]), .LD
       (clk3_counter[0]), .RB (n_21), .Q (), .QB (clk3_counter[1]));
  DFCLRBX1 \clk1_counter_reg[1] (.CK (clock), .D (clk1_counter[1]), .LD
       (clk1_counter[0]), .RB (n_21), .Q (n_1), .QB (clk1_counter[1]));
  QDFFX1 \clk1_counter_reg[0] (.CK (clock), .D (n_2), .Q
       (clk1_counter[0]));
  QDFFX1 \clk3_counter_reg[0] (.CK (clock), .D (n_4), .Q
       (clk3_counter[0]));
  DFCLRBX1 \clk2_counter_reg[1] (.CK (clock), .D (clk2_counter[1]), .LD
       (clk2_counter[0]), .RB (n_21), .Q (), .QB (clk2_counter[1]));
  AN2B1XLP g551(.I1 (n_10), .B1 (clk1_counter[2]), .O (n_11));
  DFFX1 clk1_reg56(.CK (clock), .D (n_5), .Q (), .QB (n_30));
  DFFX1 clk3_reg58(.CK (clock), .D (n_7), .Q (), .QB (n_27));
  OR4B2XLP g558(.I1 (n_1), .I2 (clk1_counter[0]), .B1
       (clk1_counter[3]), .B2 (clk1_counter[2]), .O (n_15));
  ND2X1 g553(.I1 (n_8), .I2 (clk3_internal), .O (n_9));
  OAI12X1 g562(.A1 (n_21), .B1 (enable_all), .B2 (enable_clk3), .O
       (n_7));
  OAI12X1 g563(.A1 (n_21), .B1 (enable_all), .B2 (enable_clk2), .O
       (n_6));
  OAI12X1 g564(.A1 (n_21), .B1 (enable_all), .B2 (enable_clk1), .O
       (n_5));
  OR3B2X1 g565(.I1 (clk2_counter[0]), .B1 (clk2_counter[2]), .B2
       (clk2_counter[1]), .O (n_12));
  ND2X1 g569(.I1 (clk3_counter[0]), .I2 (n_21), .O (n_4));
  ND2X1 g570(.I1 (clk2_counter[0]), .I2 (n_21), .O (n_3));
  ND2X1 g571(.I1 (clk1_counter[0]), .I2 (n_21), .O (n_2));
  AN2X1 g573(.I1 (clk1_counter[0]), .I2 (n_1), .O (n_10));
  DFFX1 clk3_reg(.CK (clock), .D (clk3_internal), .Q (), .QB (n_31));
  DFFX1 clk2_reg(.CK (clock), .D (clk2_internal), .Q (), .QB (n_32));
  DFFX1 clk1_reg(.CK (clock), .D (clk1_internal), .Q (), .QB (n_33));
  AN2B1XLP g574(.I1 (clk2_counter[0]), .B1 (clk2_counter[1]), .O (n_0));
  OR2B1XLP g572(.I1 (clk3_counter[0]), .B1 (clk3_counter[1]), .O (n_8));
  INVX1 g575(.I (reset), .O (n_21));
endmodule

