// Generated by Cadence Encounter(R) RTL Compiler RC9.1.203 - v09.10-s242_1
module clock_divider (
	clock, 
	reset, 
	enable_all, 
	enable_clk1, 
	enable_clk2, 
	enable_clk3, 
	clk1, 
	clk2, 
	clk3);
   input clock;
   input reset;
   input enable_all;
   input enable_clk1;
   input enable_clk2;
   input enable_clk3;
   output clk1;
   output clk2;
   output clk3;

   // Internal wires
   wire clock__L2_N0;
   wire clock__L1_N0;
   wire [3:0] clk1_counter;
   wire [2:0] clk2_counter;
   wire [1:0] clk3_counter;
   wire clk1_internal;
   wire clk2_internal;
   wire clk3_internal;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_27;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;

   INVCKX16 clock__L2_I0 (.O(clock__L2_N0), 
	.I(clock__L1_N0));
   INVCKX20 clock__L1_I0 (.O(clock__L1_N0), 
	.I(clock));
   DFCLRBX1 \clk1_counter_reg[3]  (.RB(n_21), 
	.QB(clk1_counter[3]), 
	.Q(), 
	.LD(n_11), 
	.D(clk1_counter[3]), 
	.CK(clock__L2_N0));
   QDFFX1 clk1_internal_reg (.Q(clk1_internal), 
	.D(n_22), 
	.CK(clock__L2_N0));
   QDFFX1 clk2_internal_reg (.Q(clk2_internal), 
	.D(n_20), 
	.CK(clock__L2_N0));
   OAI112X1 g546 (.O(n_22), 
	.C2(clk1_internal), 
	.C1(n_15), 
	.B1(n_21), 
	.A1(n_16));
   DFCLRBX1 \clk1_counter_reg[2]  (.RB(n_21), 
	.QB(clk1_counter[2]), 
	.Q(), 
	.LD(n_10), 
	.D(clk1_counter[2]), 
	.CK(clock__L2_N0));
   QDFFX1 clk3_internal_reg (.Q(clk3_internal), 
	.D(n_14), 
	.CK(clock__L2_N0));
   OAI112X1 g550 (.O(n_20), 
	.C2(clk2_internal), 
	.C1(n_12), 
	.B1(n_21), 
	.A1(n_13));
   DFCLRBX1 \clk2_counter_reg[2]  (.RB(n_21), 
	.QB(clk2_counter[2]), 
	.Q(), 
	.LD(n_0), 
	.D(clk2_counter[2]), 
	.CK(clock__L2_N0));
   INVTX1 clk1_tri (.O(clk1), 
	.I(n_33), 
	.E(n_30));
   INVTX1 clk2_tri (.O(clk2), 
	.I(n_32), 
	.E(n_29));
   INVTX1 clk3_tri (.O(clk3), 
	.I(n_31), 
	.E(n_27));
   ND2X1 g552 (.O(n_16), 
	.I2(clk1_internal), 
	.I1(n_15));
   OAI112X1 g545 (.O(n_14), 
	.C2(clk3_internal), 
	.C1(n_8), 
	.B1(n_21), 
	.A1(n_9));
   DFFX1 clk2_reg57 (.QB(n_29), 
	.Q(), 
	.D(n_6), 
	.CK(clock__L2_N0));
   ND2X1 g557 (.O(n_13), 
	.I2(clk2_internal), 
	.I1(n_12));
   QDFFX1 \clk2_counter_reg[0]  (.Q(clk2_counter[0]), 
	.D(n_3), 
	.CK(clock__L2_N0));
   DFCLRBX1 \clk3_counter_reg[1]  (.RB(n_21), 
	.QB(clk3_counter[1]), 
	.Q(), 
	.LD(clk3_counter[0]), 
	.D(clk3_counter[1]), 
	.CK(clock__L2_N0));
   DFCLRBX1 \clk1_counter_reg[1]  (.RB(n_21), 
	.QB(clk1_counter[1]), 
	.Q(n_1), 
	.LD(clk1_counter[0]), 
	.D(clk1_counter[1]), 
	.CK(clock__L2_N0));
   QDFFX1 \clk1_counter_reg[0]  (.Q(clk1_counter[0]), 
	.D(n_2), 
	.CK(clock__L2_N0));
   QDFFX1 \clk3_counter_reg[0]  (.Q(clk3_counter[0]), 
	.D(n_4), 
	.CK(clock__L2_N0));
   DFCLRBX1 \clk2_counter_reg[1]  (.RB(n_21), 
	.QB(clk2_counter[1]), 
	.Q(), 
	.LD(clk2_counter[0]), 
	.D(clk2_counter[1]), 
	.CK(clock__L2_N0));
   AN2B1XLP g551 (.O(n_11), 
	.I1(n_10), 
	.B1(clk1_counter[2]));
   DFFX1 clk1_reg56 (.QB(n_30), 
	.Q(), 
	.D(n_5), 
	.CK(clock__L2_N0));
   DFFX1 clk3_reg58 (.QB(n_27), 
	.Q(), 
	.D(n_7), 
	.CK(clock__L2_N0));
   OR4B2XLP g558 (.O(n_15), 
	.I2(clk1_counter[0]), 
	.I1(n_1), 
	.B2(clk1_counter[2]), 
	.B1(clk1_counter[3]));
   ND2X1 g553 (.O(n_9), 
	.I2(clk3_internal), 
	.I1(n_8));
   OAI12X1 g562 (.O(n_7), 
	.B2(enable_clk3), 
	.B1(enable_all), 
	.A1(n_21));
   OAI12X1 g563 (.O(n_6), 
	.B2(enable_clk2), 
	.B1(enable_all), 
	.A1(n_21));
   OAI12X1 g564 (.O(n_5), 
	.B2(enable_clk1), 
	.B1(enable_all), 
	.A1(n_21));
   OR3B2X1 g565 (.O(n_12), 
	.I1(clk2_counter[0]), 
	.B2(clk2_counter[1]), 
	.B1(clk2_counter[2]));
   ND2X1 g569 (.O(n_4), 
	.I2(n_21), 
	.I1(clk3_counter[0]));
   ND2X1 g570 (.O(n_3), 
	.I2(n_21), 
	.I1(clk2_counter[0]));
   ND2X1 g571 (.O(n_2), 
	.I2(n_21), 
	.I1(clk1_counter[0]));
   AN2X1 g573 (.O(n_10), 
	.I2(n_1), 
	.I1(clk1_counter[0]));
   DFFX1 clk3_reg (.QB(n_31), 
	.Q(), 
	.D(clk3_internal), 
	.CK(clock__L2_N0));
   DFFX1 clk2_reg (.QB(n_32), 
	.Q(), 
	.D(clk2_internal), 
	.CK(clock__L2_N0));
   DFFX1 clk1_reg (.QB(n_33), 
	.Q(), 
	.D(clk1_internal), 
	.CK(clock__L2_N0));
   AN2B1XLP g574 (.O(n_0), 
	.I1(clk2_counter[0]), 
	.B1(clk2_counter[1]));
   OR2B1XLP g572 (.O(n_8), 
	.I1(clk3_counter[0]), 
	.B1(clk3_counter[1]));
   INVX1 g575 (.O(n_21), 
	.I(reset));
endmodule

